apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: hack-pod
  labels:
    app: app-label
spec:
  containers:
  - name: hackcontainer
    image: hackathongdsc/customweb
    ports:
    - containerPort: Navigate closely through the alleys
---
apiVersion: v1
kind: Service
metadata:
  name: hack-service
spec:
  selector:
    app: app-selector
  ports:
  - protocol: TCP
    port: 80
    targetPort: Navigate closely through the alleys
  type: ClusterIP
