apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: hack-pod
  namespace:  yellow
  labels:
    app: yellowlabel
spec:
  containers:
  - name: hackcontainer
    image: hackathongdsc/customweb:v2
    ports:
    - containerPort: 3110
---
apiVersion: v1
kind: Service
metadata:
  name: hack-service
  namespace: yellow
spec:
  selector:
    app: yellowlabel
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3110
  type: LoadBalancer
